# Generated by Django 4.2.2 on 2024-10-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_admn', models.CharField(max_length=20)),
                ('Apellido_admn', models.CharField(max_length=20)),
                ('ID_admin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_cliente', models.IntegerField()),
                ('Nombre_cli', models.CharField(max_length=30)),
                ('Apellido_cli', models.CharField(max_length=30)),
                ('ID_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_compra', models.IntegerField()),
                ('ID_cliente', models.IntegerField()),
                ('ID_pago', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoComprobante', models.CharField(max_length=20)),
                ('SerieComprobante', models.CharField(max_length=7)),
                ('NumComprobante', models.CharField(max_length=10)),
                ('impuesto', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_factura', models.IntegerField()),
                ('Fecha_emision', models.DateField()),
                ('Ciudad', models.CharField(max_length=30)),
                ('Giro', models.CharField(max_length=30)),
                ('Monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_pago', models.CharField(max_length=20)),
                ('ID_pago', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_pago', models.IntegerField()),
                ('Tipo_pago', models.CharField(max_length=30)),
                ('ID_compra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_prod', models.IntegerField()),
                ('Tipo_prod', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_usuario', models.IntegerField()),
                ('Nombre_usr', models.CharField(max_length=30)),
                ('Apellido_usr', models.CharField(max_length=30)),
                ('Tipo_usr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoVenta', models.CharField(max_length=30)),
                ('Fecha', models.DateField()),
                ('Comprobante', models.CharField(max_length=30)),
                ('DetalleVenta', models.CharField(max_length=30)),
                ('ID_pago', models.IntegerField(verbose_name=2)),
                ('ID_producto', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ID_Factura', models.CharField(max_length=30)),
                ('ID_mediopago', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
