# Generated by Django 4.2.2 on 2024-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0004_alter_producto_id_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ID_prod',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Tipo_prod',
            field=models.CharField(choices=[(0, 'Linterna'), (1, 'Herramienta')], default=0, max_length=30),
        ),
    ]
