# Generated by Django 4.2.2 on 2024-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0007_alter_producto_tipo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ID_prod',
            field=models.CharField(default='001', editable=False, max_length=3, unique=True),
        ),
    ]
