# Generated by Django 4.2.2 on 2024-12-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0009_alter_producto_id_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='Tipo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEYV.tipoproducto'),
        ),
    ]
